### ISSUE TITLE
The project page doesn't load: https://convrt-2024.github.io/

### ISSUE THREAD

**Issue by samiarja** [HaomingCai/ConVRT#1]
Hi thanks for this awesome work. I am not able to load the project page. I was able to load it couple of days ago but not now. I would like to look at the output videos again, because I am working on something similar

**Comment by HaomingCai** [comment]
I double checked https://convrt-2024.github.io/    It works well now

**Comment by HaomingCai** [comment]
Webpage works well. Issue closed. Thanks for paying attention to our work
